/**
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AccountData model module.
 * @module PostPuma/model/AccountData
 * @version 1.0.0
 */
class AccountData {
    /**
     * Constructs a new <code>AccountData</code>.
     * @alias module:PostPuma/model/AccountData
     */
    constructor() { 
        
        AccountData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AccountData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PostPuma/model/AccountData} obj Optional instance to populate.
     * @return {module:PostPuma/model/AccountData} The populated <code>AccountData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AccountData();

            if (data.hasOwnProperty('union_id')) {
                obj['union_id'] = ApiClient.convertToType(data['union_id'], 'String');
            }
            if (data.hasOwnProperty('is_private')) {
                obj['is_private'] = ApiClient.convertToType(data['is_private'], 'Boolean');
            }
            if (data.hasOwnProperty('duet_disabled')) {
                obj['duet_disabled'] = ApiClient.convertToType(data['duet_disabled'], 'Boolean');
            }
            if (data.hasOwnProperty('privacy_levels')) {
                obj['privacy_levels'] = ApiClient.convertToType(data['privacy_levels'], ['String']);
            }
            if (data.hasOwnProperty('stitch_disabled')) {
                obj['stitch_disabled'] = ApiClient.convertToType(data['stitch_disabled'], 'Boolean');
            }
            if (data.hasOwnProperty('comment_disabled')) {
                obj['comment_disabled'] = ApiClient.convertToType(data['comment_disabled'], 'Boolean');
            }
            if (data.hasOwnProperty('max_video_post_duration_sec')) {
                obj['max_video_post_duration_sec'] = ApiClient.convertToType(data['max_video_post_duration_sec'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AccountData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AccountData</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['union_id'] && !(typeof data['union_id'] === 'string' || data['union_id'] instanceof String)) {
            throw new Error("Expected the field `union_id` to be a primitive type in the JSON string but got " + data['union_id']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['privacy_levels'])) {
            throw new Error("Expected the field `privacy_levels` to be an array in the JSON data but got " + data['privacy_levels']);
        }

        return true;
    }


}



/**
 * @member {String} union_id
 */
AccountData.prototype['union_id'] = undefined;

/**
 * @member {Boolean} is_private
 */
AccountData.prototype['is_private'] = undefined;

/**
 * @member {Boolean} duet_disabled
 */
AccountData.prototype['duet_disabled'] = undefined;

/**
 * @member {Array.<String>} privacy_levels
 */
AccountData.prototype['privacy_levels'] = undefined;

/**
 * @member {Boolean} stitch_disabled
 */
AccountData.prototype['stitch_disabled'] = undefined;

/**
 * @member {Boolean} comment_disabled
 */
AccountData.prototype['comment_disabled'] = undefined;

/**
 * @member {Number} max_video_post_duration_sec
 */
AccountData.prototype['max_video_post_duration_sec'] = undefined;






export default AccountData;

