/**
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DeletePostsRequest model module.
 * @module PostPuma/model/DeletePostsRequest
 * @version 1.0.0
 */
class DeletePostsRequest {
    /**
     * Constructs a new <code>DeletePostsRequest</code>.
     * @alias module:PostPuma/model/DeletePostsRequest
     * @param posts {Array.<String>} Post UUIDs
     */
    constructor(posts) { 
        
        DeletePostsRequest.initialize(this, posts);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, posts) { 
        obj['posts'] = posts;
    }

    /**
     * Constructs a <code>DeletePostsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PostPuma/model/DeletePostsRequest} obj Optional instance to populate.
     * @return {module:PostPuma/model/DeletePostsRequest} The populated <code>DeletePostsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeletePostsRequest();

            if (data.hasOwnProperty('posts')) {
                obj['posts'] = ApiClient.convertToType(data['posts'], ['String']);
            }
            if (data.hasOwnProperty('trash')) {
                obj['trash'] = ApiClient.convertToType(data['trash'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DeletePostsRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DeletePostsRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DeletePostsRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['posts'])) {
            throw new Error("Expected the field `posts` to be an array in the JSON data but got " + data['posts']);
        }

        return true;
    }


}

DeletePostsRequest.RequiredProperties = ["posts"];

/**
 * Post UUIDs
 * @member {Array.<String>} posts
 */
DeletePostsRequest.prototype['posts'] = undefined;

/**
 * @member {Boolean} trash
 */
DeletePostsRequest.prototype['trash'] = undefined;






export default DeletePostsRequest;

