/**
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DeleteMediaFilesRequest model module.
 * @module PostPuma/model/DeleteMediaFilesRequest
 * @version 1.0.0
 */
class DeleteMediaFilesRequest {
    /**
     * Constructs a new <code>DeleteMediaFilesRequest</code>.
     * @alias module:PostPuma/model/DeleteMediaFilesRequest
     * @param items {Array.<Number>} File IDs
     */
    constructor(items) { 
        
        DeleteMediaFilesRequest.initialize(this, items);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, items) { 
        obj['items'] = items;
    }

    /**
     * Constructs a <code>DeleteMediaFilesRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PostPuma/model/DeleteMediaFilesRequest} obj Optional instance to populate.
     * @return {module:PostPuma/model/DeleteMediaFilesRequest} The populated <code>DeleteMediaFilesRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeleteMediaFilesRequest();

            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], ['Number']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DeleteMediaFilesRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DeleteMediaFilesRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DeleteMediaFilesRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['items'])) {
            throw new Error("Expected the field `items` to be an array in the JSON data but got " + data['items']);
        }

        return true;
    }


}

DeleteMediaFilesRequest.RequiredProperties = ["items"];

/**
 * File IDs
 * @member {Array.<Number>} items
 */
DeleteMediaFilesRequest.prototype['items'] = undefined;






export default DeleteMediaFilesRequest;

