/**
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DeleteMediaFiles200Response model module.
 * @module PostPuma/model/DeleteMediaFiles200Response
 * @version 1.0.0
 */
class DeleteMediaFiles200Response {
    /**
     * Constructs a new <code>DeleteMediaFiles200Response</code>.
     * @alias module:PostPuma/model/DeleteMediaFiles200Response
     */
    constructor() { 
        
        DeleteMediaFiles200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DeleteMediaFiles200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PostPuma/model/DeleteMediaFiles200Response} obj Optional instance to populate.
     * @return {module:PostPuma/model/DeleteMediaFiles200Response} The populated <code>DeleteMediaFiles200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeleteMediaFiles200Response();

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DeleteMediaFiles200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DeleteMediaFiles200Response</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Boolean} success
 */
DeleteMediaFiles200Response.prototype['success'] = undefined;






export default DeleteMediaFiles200Response;

