/**
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DeletePosts200ResponseOneOf from './DeletePosts200ResponseOneOf';
import DeletePosts200ResponseOneOf1 from './DeletePosts200ResponseOneOf1';

/**
 * The DeletePosts200Response model module.
 * @module PostPuma/model/DeletePosts200Response
 * @version 1.0.0
 */
class DeletePosts200Response {
    /**
     * Constructs a new <code>DeletePosts200Response</code>.
     * @alias module:PostPuma/model/DeletePosts200Response
     * @param {(module:PostPuma/model/DeletePosts200ResponseOneOf|module:PostPuma/model/DeletePosts200ResponseOneOf1)} instance The actual instance to initialize DeletePosts200Response.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (typeof instance === "DeletePosts200ResponseOneOf") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                DeletePosts200ResponseOneOf.validateJSON(instance); // throw an exception if no match
                // create DeletePosts200ResponseOneOf from JS object
                this.actualInstance = DeletePosts200ResponseOneOf.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into DeletePosts200ResponseOneOf
            errorMessages.push("Failed to construct DeletePosts200ResponseOneOf: " + err)
        }

        try {
            if (typeof instance === "DeletePosts200ResponseOneOf1") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                DeletePosts200ResponseOneOf1.validateJSON(instance); // throw an exception if no match
                // create DeletePosts200ResponseOneOf1 from JS object
                this.actualInstance = DeletePosts200ResponseOneOf1.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into DeletePosts200ResponseOneOf1
            errorMessages.push("Failed to construct DeletePosts200ResponseOneOf1: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `DeletePosts200Response` with oneOf schemas DeletePosts200ResponseOneOf, DeletePosts200ResponseOneOf1. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `DeletePosts200Response` with oneOf schemas DeletePosts200ResponseOneOf, DeletePosts200ResponseOneOf1. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>DeletePosts200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PostPuma/model/DeletePosts200Response} obj Optional instance to populate.
     * @return {module:PostPuma/model/DeletePosts200Response} The populated <code>DeletePosts200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        return new DeletePosts200Response(data);
    }

    /**
     * Gets the actual instance, which can be <code>DeletePosts200ResponseOneOf</code>, <code>DeletePosts200ResponseOneOf1</code>.
     * @return {(module:PostPuma/model/DeletePosts200ResponseOneOf|module:PostPuma/model/DeletePosts200ResponseOneOf1)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>DeletePosts200ResponseOneOf</code>, <code>DeletePosts200ResponseOneOf1</code>.
     * @param {(module:PostPuma/model/DeletePosts200ResponseOneOf|module:PostPuma/model/DeletePosts200ResponseOneOf1)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = DeletePosts200Response.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of DeletePosts200Response from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:PostPuma/model/DeletePosts200Response} An instance of DeletePosts200Response.
     */
    static fromJSON = function(json_string){
        return DeletePosts200Response.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {Boolean} deleted
 */
DeletePosts200Response.prototype['deleted'] = undefined;

/**
 * @member {Boolean} to_trash
 */
DeletePosts200Response.prototype['to_trash'] = undefined;


DeletePosts200Response.OneOf = ["DeletePosts200ResponseOneOf", "DeletePosts200ResponseOneOf1"];

export default DeletePosts200Response;

