/**
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DeletePostRequest model module.
 * @module PostPuma/model/DeletePostRequest
 * @version 1.0.0
 */
class DeletePostRequest {
    /**
     * Constructs a new <code>DeletePostRequest</code>.
     * @alias module:PostPuma/model/DeletePostRequest
     */
    constructor() { 
        
        DeletePostRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DeletePostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PostPuma/model/DeletePostRequest} obj Optional instance to populate.
     * @return {module:PostPuma/model/DeletePostRequest} The populated <code>DeletePostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeletePostRequest();

            if (data.hasOwnProperty('trash')) {
                obj['trash'] = ApiClient.convertToType(data['trash'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DeletePostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DeletePostRequest</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Whether to move items to trash or not.
 * @member {Boolean} trash
 */
DeletePostRequest.prototype['trash'] = undefined;






export default DeletePostRequest;

