/**
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Account from './Account';

/**
 * The ListAccounts200Response model module.
 * @module PostPuma/model/ListAccounts200Response
 * @version 1.0.0
 */
class ListAccounts200Response {
    /**
     * Constructs a new <code>ListAccounts200Response</code>.
     * @alias module:PostPuma/model/ListAccounts200Response
     */
    constructor() { 
        
        ListAccounts200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ListAccounts200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PostPuma/model/ListAccounts200Response} obj Optional instance to populate.
     * @return {module:PostPuma/model/ListAccounts200Response} The populated <code>ListAccounts200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListAccounts200Response();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [Account]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ListAccounts200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ListAccounts200Response</code>.
     */
    static validateJSON(data) {
        if (data['data']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['data'])) {
                throw new Error("Expected the field `data` to be an array in the JSON data but got " + data['data']);
            }
            // validate the optional field `data` (array)
            for (const item of data['data']) {
                Account.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:PostPuma/model/Account>} data
 */
ListAccounts200Response.prototype['data'] = undefined;






export default ListAccounts200Response;

