/**
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SchedulePostRequest model module.
 * @module PostPuma/model/SchedulePostRequest
 * @version 1.0.0
 */
class SchedulePostRequest {
    /**
     * Constructs a new <code>SchedulePostRequest</code>.
     * @alias module:PostPuma/model/SchedulePostRequest
     * @param postNow {Boolean} 
     */
    constructor(postNow) { 
        
        SchedulePostRequest.initialize(this, postNow);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, postNow) { 
        obj['postNow'] = postNow;
    }

    /**
     * Constructs a <code>SchedulePostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PostPuma/model/SchedulePostRequest} obj Optional instance to populate.
     * @return {module:PostPuma/model/SchedulePostRequest} The populated <code>SchedulePostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SchedulePostRequest();

            if (data.hasOwnProperty('postNow')) {
                obj['postNow'] = ApiClient.convertToType(data['postNow'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SchedulePostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SchedulePostRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SchedulePostRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

SchedulePostRequest.RequiredProperties = ["postNow"];

/**
 * @member {Boolean} postNow
 */
SchedulePostRequest.prototype['postNow'] = undefined;






export default SchedulePostRequest;

