/**
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import VersionOptionsInstagram from './VersionOptionsInstagram';
import VersionOptionsLinkedin from './VersionOptionsLinkedin';
import VersionOptionsMastodon from './VersionOptionsMastodon';
import VersionOptionsPinterest from './VersionOptionsPinterest';
import VersionOptionsTiktok from './VersionOptionsTiktok';
import VersionOptionsYoutube from './VersionOptionsYoutube';

/**
 * The VersionOptions model module.
 * @module PostPuma/model/VersionOptions
 * @version 1.0.0
 */
class VersionOptions {
    /**
     * Constructs a new <code>VersionOptions</code>.
     * @alias module:PostPuma/model/VersionOptions
     */
    constructor() { 
        
        VersionOptions.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VersionOptions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PostPuma/model/VersionOptions} obj Optional instance to populate.
     * @return {module:PostPuma/model/VersionOptions} The populated <code>VersionOptions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VersionOptions();

            if (data.hasOwnProperty('tiktok')) {
                obj['tiktok'] = VersionOptionsTiktok.constructFromObject(data['tiktok']);
            }
            if (data.hasOwnProperty('youtube')) {
                obj['youtube'] = VersionOptionsYoutube.constructFromObject(data['youtube']);
            }
            if (data.hasOwnProperty('linkedin')) {
                obj['linkedin'] = VersionOptionsLinkedin.constructFromObject(data['linkedin']);
            }
            if (data.hasOwnProperty('mastodon')) {
                obj['mastodon'] = VersionOptionsMastodon.constructFromObject(data['mastodon']);
            }
            if (data.hasOwnProperty('instagram')) {
                obj['instagram'] = VersionOptionsInstagram.constructFromObject(data['instagram']);
            }
            if (data.hasOwnProperty('pinterest')) {
                obj['pinterest'] = VersionOptionsPinterest.constructFromObject(data['pinterest']);
            }
            if (data.hasOwnProperty('facebook_page')) {
                obj['facebook_page'] = VersionOptionsInstagram.constructFromObject(data['facebook_page']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VersionOptions</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VersionOptions</code>.
     */
    static validateJSON(data) {
        // validate the optional field `tiktok`
        if (data['tiktok']) { // data not null
          VersionOptionsTiktok.validateJSON(data['tiktok']);
        }
        // validate the optional field `youtube`
        if (data['youtube']) { // data not null
          VersionOptionsYoutube.validateJSON(data['youtube']);
        }
        // validate the optional field `linkedin`
        if (data['linkedin']) { // data not null
          VersionOptionsLinkedin.validateJSON(data['linkedin']);
        }
        // validate the optional field `mastodon`
        if (data['mastodon']) { // data not null
          VersionOptionsMastodon.validateJSON(data['mastodon']);
        }
        // validate the optional field `instagram`
        if (data['instagram']) { // data not null
          VersionOptionsInstagram.validateJSON(data['instagram']);
        }
        // validate the optional field `pinterest`
        if (data['pinterest']) { // data not null
          VersionOptionsPinterest.validateJSON(data['pinterest']);
        }
        // validate the optional field `facebook_page`
        if (data['facebook_page']) { // data not null
          VersionOptionsInstagram.validateJSON(data['facebook_page']);
        }

        return true;
    }


}



/**
 * @member {module:PostPuma/model/VersionOptionsTiktok} tiktok
 */
VersionOptions.prototype['tiktok'] = undefined;

/**
 * @member {module:PostPuma/model/VersionOptionsYoutube} youtube
 */
VersionOptions.prototype['youtube'] = undefined;

/**
 * @member {module:PostPuma/model/VersionOptionsLinkedin} linkedin
 */
VersionOptions.prototype['linkedin'] = undefined;

/**
 * @member {module:PostPuma/model/VersionOptionsMastodon} mastodon
 */
VersionOptions.prototype['mastodon'] = undefined;

/**
 * @member {module:PostPuma/model/VersionOptionsInstagram} instagram
 */
VersionOptions.prototype['instagram'] = undefined;

/**
 * @member {module:PostPuma/model/VersionOptionsPinterest} pinterest
 */
VersionOptions.prototype['pinterest'] = undefined;

/**
 * @member {module:PostPuma/model/VersionOptionsInstagram} facebook_page
 */
VersionOptions.prototype['facebook_page'] = undefined;






export default VersionOptions;

