/**
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VersionOptionsYoutube model module.
 * @module PostPuma/model/VersionOptionsYoutube
 * @version 1.0.0
 */
class VersionOptionsYoutube {
    /**
     * Constructs a new <code>VersionOptionsYoutube</code>.
     * @alias module:PostPuma/model/VersionOptionsYoutube
     */
    constructor() { 
        
        VersionOptionsYoutube.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VersionOptionsYoutube</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PostPuma/model/VersionOptionsYoutube} obj Optional instance to populate.
     * @return {module:PostPuma/model/VersionOptionsYoutube} The populated <code>VersionOptionsYoutube</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VersionOptionsYoutube();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VersionOptionsYoutube</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VersionOptionsYoutube</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }

        return true;
    }


}



/**
 * @member {String} title
 */
VersionOptionsYoutube.prototype['title'] = undefined;

/**
 * @member {String} status
 */
VersionOptionsYoutube.prototype['status'] = undefined;






export default VersionOptionsYoutube;

