/**
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VersionOptionsPinterestBoards model module.
 * @module PostPuma/model/VersionOptionsPinterestBoards
 * @version 1.0.0
 */
class VersionOptionsPinterestBoards {
    /**
     * Constructs a new <code>VersionOptionsPinterestBoards</code>.
     * @alias module:PostPuma/model/VersionOptionsPinterestBoards
     */
    constructor() { 
        
        VersionOptionsPinterestBoards.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VersionOptionsPinterestBoards</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PostPuma/model/VersionOptionsPinterestBoards} obj Optional instance to populate.
     * @return {module:PostPuma/model/VersionOptionsPinterestBoards} The populated <code>VersionOptionsPinterestBoards</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VersionOptionsPinterestBoards();

            if (data.hasOwnProperty('accounts-0')) {
                obj['accounts-0'] = ApiClient.convertToType(data['accounts-0'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VersionOptionsPinterestBoards</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VersionOptionsPinterestBoards</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['accounts-0'] && !(typeof data['accounts-0'] === 'string' || data['accounts-0'] instanceof String)) {
            throw new Error("Expected the field `accounts-0` to be a primitive type in the JSON string but got " + data['accounts-0']);
        }

        return true;
    }


}



/**
 * @member {String} accounts-0
 */
VersionOptionsPinterestBoards.prototype['accounts-0'] = undefined;






export default VersionOptionsPinterestBoards;

