/**
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VersionOptionsMastodon model module.
 * @module PostPuma/model/VersionOptionsMastodon
 * @version 1.0.0
 */
class VersionOptionsMastodon {
    /**
     * Constructs a new <code>VersionOptionsMastodon</code>.
     * @alias module:PostPuma/model/VersionOptionsMastodon
     */
    constructor() { 
        
        VersionOptionsMastodon.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VersionOptionsMastodon</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PostPuma/model/VersionOptionsMastodon} obj Optional instance to populate.
     * @return {module:PostPuma/model/VersionOptionsMastodon} The populated <code>VersionOptionsMastodon</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VersionOptionsMastodon();

            if (data.hasOwnProperty('sensitive')) {
                obj['sensitive'] = ApiClient.convertToType(data['sensitive'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VersionOptionsMastodon</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VersionOptionsMastodon</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Boolean} sensitive
 */
VersionOptionsMastodon.prototype['sensitive'] = undefined;






export default VersionOptionsMastodon;

