/**
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import VersionOptionsTiktokPrivacyLevel from './VersionOptionsTiktokPrivacyLevel';

/**
 * The VersionOptionsTiktok model module.
 * @module PostPuma/model/VersionOptionsTiktok
 * @version 1.0.0
 */
class VersionOptionsTiktok {
    /**
     * Constructs a new <code>VersionOptionsTiktok</code>.
     * @alias module:PostPuma/model/VersionOptionsTiktok
     */
    constructor() { 
        
        VersionOptionsTiktok.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VersionOptionsTiktok</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PostPuma/model/VersionOptionsTiktok} obj Optional instance to populate.
     * @return {module:PostPuma/model/VersionOptionsTiktok} The populated <code>VersionOptionsTiktok</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VersionOptionsTiktok();

            if (data.hasOwnProperty('privacy_level')) {
                obj['privacy_level'] = VersionOptionsTiktokPrivacyLevel.constructFromObject(data['privacy_level']);
            }
            if (data.hasOwnProperty('allow_comments')) {
                obj['allow_comments'] = VersionOptionsTiktokPrivacyLevel.constructFromObject(data['allow_comments']);
            }
            if (data.hasOwnProperty('allow_duet')) {
                obj['allow_duet'] = VersionOptionsTiktokPrivacyLevel.constructFromObject(data['allow_duet']);
            }
            if (data.hasOwnProperty('allow_stitch')) {
                obj['allow_stitch'] = VersionOptionsTiktokPrivacyLevel.constructFromObject(data['allow_stitch']);
            }
            if (data.hasOwnProperty('content_disclosure')) {
                obj['content_disclosure'] = VersionOptionsTiktokPrivacyLevel.constructFromObject(data['content_disclosure']);
            }
            if (data.hasOwnProperty('brand_organic_toggle')) {
                obj['brand_organic_toggle'] = VersionOptionsTiktokPrivacyLevel.constructFromObject(data['brand_organic_toggle']);
            }
            if (data.hasOwnProperty('brand_content_toggle')) {
                obj['brand_content_toggle'] = VersionOptionsTiktokPrivacyLevel.constructFromObject(data['brand_content_toggle']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VersionOptionsTiktok</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VersionOptionsTiktok</code>.
     */
    static validateJSON(data) {
        // validate the optional field `privacy_level`
        if (data['privacy_level']) { // data not null
          VersionOptionsTiktokPrivacyLevel.validateJSON(data['privacy_level']);
        }
        // validate the optional field `allow_comments`
        if (data['allow_comments']) { // data not null
          VersionOptionsTiktokPrivacyLevel.validateJSON(data['allow_comments']);
        }
        // validate the optional field `allow_duet`
        if (data['allow_duet']) { // data not null
          VersionOptionsTiktokPrivacyLevel.validateJSON(data['allow_duet']);
        }
        // validate the optional field `allow_stitch`
        if (data['allow_stitch']) { // data not null
          VersionOptionsTiktokPrivacyLevel.validateJSON(data['allow_stitch']);
        }
        // validate the optional field `content_disclosure`
        if (data['content_disclosure']) { // data not null
          VersionOptionsTiktokPrivacyLevel.validateJSON(data['content_disclosure']);
        }
        // validate the optional field `brand_organic_toggle`
        if (data['brand_organic_toggle']) { // data not null
          VersionOptionsTiktokPrivacyLevel.validateJSON(data['brand_organic_toggle']);
        }
        // validate the optional field `brand_content_toggle`
        if (data['brand_content_toggle']) { // data not null
          VersionOptionsTiktokPrivacyLevel.validateJSON(data['brand_content_toggle']);
        }

        return true;
    }


}



/**
 * @member {module:PostPuma/model/VersionOptionsTiktokPrivacyLevel} privacy_level
 */
VersionOptionsTiktok.prototype['privacy_level'] = undefined;

/**
 * @member {module:PostPuma/model/VersionOptionsTiktokPrivacyLevel} allow_comments
 */
VersionOptionsTiktok.prototype['allow_comments'] = undefined;

/**
 * @member {module:PostPuma/model/VersionOptionsTiktokPrivacyLevel} allow_duet
 */
VersionOptionsTiktok.prototype['allow_duet'] = undefined;

/**
 * @member {module:PostPuma/model/VersionOptionsTiktokPrivacyLevel} allow_stitch
 */
VersionOptionsTiktok.prototype['allow_stitch'] = undefined;

/**
 * @member {module:PostPuma/model/VersionOptionsTiktokPrivacyLevel} content_disclosure
 */
VersionOptionsTiktok.prototype['content_disclosure'] = undefined;

/**
 * @member {module:PostPuma/model/VersionOptionsTiktokPrivacyLevel} brand_organic_toggle
 */
VersionOptionsTiktok.prototype['brand_organic_toggle'] = undefined;

/**
 * @member {module:PostPuma/model/VersionOptionsTiktokPrivacyLevel} brand_content_toggle
 */
VersionOptionsTiktok.prototype['brand_content_toggle'] = undefined;






export default VersionOptionsTiktok;

