/**
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VersionOptionsTiktokPrivacyLevel model module.
 * @module PostPuma/model/VersionOptionsTiktokPrivacyLevel
 * @version 1.0.0
 */
class VersionOptionsTiktokPrivacyLevel {
    /**
     * Constructs a new <code>VersionOptionsTiktokPrivacyLevel</code>.
     * @alias module:PostPuma/model/VersionOptionsTiktokPrivacyLevel
     */
    constructor() { 
        
        VersionOptionsTiktokPrivacyLevel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VersionOptionsTiktokPrivacyLevel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PostPuma/model/VersionOptionsTiktokPrivacyLevel} obj Optional instance to populate.
     * @return {module:PostPuma/model/VersionOptionsTiktokPrivacyLevel} The populated <code>VersionOptionsTiktokPrivacyLevel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VersionOptionsTiktokPrivacyLevel();

            if (data.hasOwnProperty('account-0')) {
                obj['account-0'] = ApiClient.convertToType(data['account-0'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VersionOptionsTiktokPrivacyLevel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VersionOptionsTiktokPrivacyLevel</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Boolean} account-0
 */
VersionOptionsTiktokPrivacyLevel.prototype['account-0'] = undefined;






export default VersionOptionsTiktokPrivacyLevel;

