/**
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Account from './model/Account';
import AccountData from './model/AccountData';
import CreatePostRequest from './model/CreatePostRequest';
import CreateTagRequest from './model/CreateTagRequest';
import DeleteMediaFiles200Response from './model/DeleteMediaFiles200Response';
import DeleteMediaFilesRequest from './model/DeleteMediaFilesRequest';
import DeletePostRequest from './model/DeletePostRequest';
import DeletePosts200Response from './model/DeletePosts200Response';
import DeletePosts200ResponseOneOf from './model/DeletePosts200ResponseOneOf';
import DeletePosts200ResponseOneOf1 from './model/DeletePosts200ResponseOneOf1';
import DeletePostsRequest from './model/DeletePostsRequest';
import ListAccounts200Response from './model/ListAccounts200Response';
import ListMediaFiles200Response from './model/ListMediaFiles200Response';
import ListPosts200Response from './model/ListPosts200Response';
import ListTags200Response from './model/ListTags200Response';
import MediaFile from './model/MediaFile';
import Post from './model/Post';
import PostUser from './model/PostUser';
import QueuePost200Response from './model/QueuePost200Response';
import SchedulePostRequest from './model/SchedulePostRequest';
import Tag from './model/Tag';
import UpdatePostRequest from './model/UpdatePostRequest';
import UpdateTagRequest from './model/UpdateTagRequest';
import Version from './model/Version';
import VersionContent from './model/VersionContent';
import VersionOptions from './model/VersionOptions';
import VersionOptionsInstagram from './model/VersionOptionsInstagram';
import VersionOptionsLinkedin from './model/VersionOptionsLinkedin';
import VersionOptionsMastodon from './model/VersionOptionsMastodon';
import VersionOptionsPinterest from './model/VersionOptionsPinterest';
import VersionOptionsPinterestBoards from './model/VersionOptionsPinterestBoards';
import VersionOptionsTiktok from './model/VersionOptionsTiktok';
import VersionOptionsTiktokPrivacyLevel from './model/VersionOptionsTiktokPrivacyLevel';
import VersionOptionsYoutube from './model/VersionOptionsYoutube';
import AccountsApi from './PostPuma/AccountsApi';
import MediaApi from './PostPuma/MediaApi';
import PostsApi from './PostPuma/PostsApi';
import TagsApi from './PostPuma/TagsApi';


/**
* PostPuma API specifications.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var PostPumaOpenApi30 = require('PostPuma/index'); // See note below*.
* var xxxSvc = new PostPumaOpenApi30.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new PostPumaOpenApi30.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['PostPuma/index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new PostPumaOpenApi30.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new PostPumaOpenApi30.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module PostPuma/index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:PostPuma/ApiClient}
     */
    ApiClient,

    /**
     * The Account model constructor.
     * @property {module:PostPuma/model/Account}
     */
    Account,

    /**
     * The AccountData model constructor.
     * @property {module:PostPuma/model/AccountData}
     */
    AccountData,

    /**
     * The CreatePostRequest model constructor.
     * @property {module:PostPuma/model/CreatePostRequest}
     */
    CreatePostRequest,

    /**
     * The CreateTagRequest model constructor.
     * @property {module:PostPuma/model/CreateTagRequest}
     */
    CreateTagRequest,

    /**
     * The DeleteMediaFiles200Response model constructor.
     * @property {module:PostPuma/model/DeleteMediaFiles200Response}
     */
    DeleteMediaFiles200Response,

    /**
     * The DeleteMediaFilesRequest model constructor.
     * @property {module:PostPuma/model/DeleteMediaFilesRequest}
     */
    DeleteMediaFilesRequest,

    /**
     * The DeletePostRequest model constructor.
     * @property {module:PostPuma/model/DeletePostRequest}
     */
    DeletePostRequest,

    /**
     * The DeletePosts200Response model constructor.
     * @property {module:PostPuma/model/DeletePosts200Response}
     */
    DeletePosts200Response,

    /**
     * The DeletePosts200ResponseOneOf model constructor.
     * @property {module:PostPuma/model/DeletePosts200ResponseOneOf}
     */
    DeletePosts200ResponseOneOf,

    /**
     * The DeletePosts200ResponseOneOf1 model constructor.
     * @property {module:PostPuma/model/DeletePosts200ResponseOneOf1}
     */
    DeletePosts200ResponseOneOf1,

    /**
     * The DeletePostsRequest model constructor.
     * @property {module:PostPuma/model/DeletePostsRequest}
     */
    DeletePostsRequest,

    /**
     * The ListAccounts200Response model constructor.
     * @property {module:PostPuma/model/ListAccounts200Response}
     */
    ListAccounts200Response,

    /**
     * The ListMediaFiles200Response model constructor.
     * @property {module:PostPuma/model/ListMediaFiles200Response}
     */
    ListMediaFiles200Response,

    /**
     * The ListPosts200Response model constructor.
     * @property {module:PostPuma/model/ListPosts200Response}
     */
    ListPosts200Response,

    /**
     * The ListTags200Response model constructor.
     * @property {module:PostPuma/model/ListTags200Response}
     */
    ListTags200Response,

    /**
     * The MediaFile model constructor.
     * @property {module:PostPuma/model/MediaFile}
     */
    MediaFile,

    /**
     * The Post model constructor.
     * @property {module:PostPuma/model/Post}
     */
    Post,

    /**
     * The PostUser model constructor.
     * @property {module:PostPuma/model/PostUser}
     */
    PostUser,

    /**
     * The QueuePost200Response model constructor.
     * @property {module:PostPuma/model/QueuePost200Response}
     */
    QueuePost200Response,

    /**
     * The SchedulePostRequest model constructor.
     * @property {module:PostPuma/model/SchedulePostRequest}
     */
    SchedulePostRequest,

    /**
     * The Tag model constructor.
     * @property {module:PostPuma/model/Tag}
     */
    Tag,

    /**
     * The UpdatePostRequest model constructor.
     * @property {module:PostPuma/model/UpdatePostRequest}
     */
    UpdatePostRequest,

    /**
     * The UpdateTagRequest model constructor.
     * @property {module:PostPuma/model/UpdateTagRequest}
     */
    UpdateTagRequest,

    /**
     * The Version model constructor.
     * @property {module:PostPuma/model/Version}
     */
    Version,

    /**
     * The VersionContent model constructor.
     * @property {module:PostPuma/model/VersionContent}
     */
    VersionContent,

    /**
     * The VersionOptions model constructor.
     * @property {module:PostPuma/model/VersionOptions}
     */
    VersionOptions,

    /**
     * The VersionOptionsInstagram model constructor.
     * @property {module:PostPuma/model/VersionOptionsInstagram}
     */
    VersionOptionsInstagram,

    /**
     * The VersionOptionsLinkedin model constructor.
     * @property {module:PostPuma/model/VersionOptionsLinkedin}
     */
    VersionOptionsLinkedin,

    /**
     * The VersionOptionsMastodon model constructor.
     * @property {module:PostPuma/model/VersionOptionsMastodon}
     */
    VersionOptionsMastodon,

    /**
     * The VersionOptionsPinterest model constructor.
     * @property {module:PostPuma/model/VersionOptionsPinterest}
     */
    VersionOptionsPinterest,

    /**
     * The VersionOptionsPinterestBoards model constructor.
     * @property {module:PostPuma/model/VersionOptionsPinterestBoards}
     */
    VersionOptionsPinterestBoards,

    /**
     * The VersionOptionsTiktok model constructor.
     * @property {module:PostPuma/model/VersionOptionsTiktok}
     */
    VersionOptionsTiktok,

    /**
     * The VersionOptionsTiktokPrivacyLevel model constructor.
     * @property {module:PostPuma/model/VersionOptionsTiktokPrivacyLevel}
     */
    VersionOptionsTiktokPrivacyLevel,

    /**
     * The VersionOptionsYoutube model constructor.
     * @property {module:PostPuma/model/VersionOptionsYoutube}
     */
    VersionOptionsYoutube,

    /**
    * The AccountsApi service constructor.
    * @property {module:PostPuma/PostPuma/AccountsApi}
    */
    AccountsApi,

    /**
    * The MediaApi service constructor.
    * @property {module:PostPuma/PostPuma/MediaApi}
    */
    MediaApi,

    /**
    * The PostsApi service constructor.
    * @property {module:PostPuma/PostPuma/PostsApi}
    */
    PostsApi,

    /**
    * The TagsApi service constructor.
    * @property {module:PostPuma/PostPuma/TagsApi}
    */
    TagsApi
};
